# This file is strictly used for the harness pod container image, and allows
# this directory to be installed as a package and the CLI to be executed with
# "benchmark-report".
#
# This is done by copying this directory to /opt, moving this file to
# /opt/pyproject.toml, then doing "pip install -e /opt".
#
# This file will not do anything useful as-is in its current location.

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "benchmark-report"
version = "0.1.0"

[project.scripts]
benchmark-report = "benchmark_report.cli:main"

[tool.setuptools.packages.find]
include = ["benchmark_report"]
